### PR TITLE
Dev new search fn

### PR DESCRIPTION
**Pull request by SteveViss**
New functions (issue #29 & #46 )
- `search_interactions()`
- `search_taxa()`

### CODE REVIEW

**Comment by KevCaz** [comment]
I'll have a look now :)

**Review by KevCaz — CHANGES_REQUESTED** [review]
- queries via tsn, eol, bold or ncbi + tests
- `...` should be added ==> httr::GET()

**Comment by KevCaz** [comment]
argument `expand_node` in `search_interactions()` is great but so far if it `TRUE` then columns `node_from` and `node_to` are vectors of integers whereas when it is set to `FALSE` there are data frames, which I think is quite confusing for the users. I would rather use a function to merge the data frames when `expand_node = TRUE`. What do you think @SteveViss ?

**Comment by KevCaz** [comment]
`query$count <- limit` in `get_gen()` ==>  always coerces `query` to a list if `query` is not a list. I think you should add `query <- as.list(query)` so to control the conversion.

**Comment by SteveViss** [comment]
First comment: Ok with merging `data.frame`. Could you rename the columns?

Second comment: `query` is always supposed to be a `list` in `get_gen()` otherwise `httr::GET` will not take it.

**Comment by SteveViss** [comment]
I see your point with `as.list`. I'm ok with that.

**Comment by KevCaz** [comment]
I got an issue when testing `get_collection()`:

```R
R> get_collection(search_taxa("Acer"))
Found 5 taxa
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match
```

**Comment by KevCaz** [comment]
> Could you rename the columns?

Yes but what are the new names?

**Comment by SteveViss** [comment]
In fact, you dont have to rename the columns. The `expand_node` will add new ones and the names should be preserved to match the one from the API. What do you think?

**Comment by KevCaz** [comment]
I'll try this!

**Comment by KevCaz** [comment]
@SteveViss the merge is more tricky than I expected, we also have to take care of how we merge network. Maybe we can work on this in another PR. I think we can merge this one, and work on the next one.

**Review by KevCaz — APPROVED** [review]

**Pull request merged**
